apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: rancher-apps
  namespace: fleet-local
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: rancher-apps
    meta.helm.sh/release-namespace: weapps
spec:
  repo: https://github.com/FoeT/rancher-apps
  branch: main
  paths:
  - .
  helmRepoURLRegex: "https://charts.*"
  clientSecretName: foet-git
  forceSyncGeneration: 0
  correctDrift:
    enabled: true
  targets:
  - clusterName: local
