apiVersion: v1
kind: Service
metadata:
  name: exchat-dev-service
  namespace: weapps
spec:
  selector:
    app: exchat-dev-workload
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: exchat-dev-service-ingress
  namespace: weapps
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  rules:
  - host: exchatdev.mynetapp.site
    http:
      paths:
      - pathType: ImplementationSpecific
        backend:
          service:
            name: nginx-service
            port:
              number: 80
  tls:
  - hosts:
    - exchatdev.mynetapp.site
    secretName: mynetapp-site-production-tls
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: exchat-dev-deployment
  namespace: weapps
spec:
  selector:
    matchLabels:
      app: exchat-dev-workload
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: exchat-dev-workload
    spec:    
      containers:
      - envFrom:
        - secretRef:
            name: exchat-secrets
            optional: false
        image: python:3.10
        imagePullPolicy: Always
        name: exchat-dev-workload
        stdin: true
        ports:
        - containerPort: 8000
          name: exchat-dev-port
          protocol: TCP
        - containerPort: 22   # The new SSH port
          name: ssh
          protocol: TCP            
        volumeMounts:
        - mountPath: /var/www/exchat
          name: pinas-root
          subPath: scripts/git/Exchat_Social_Network            
        - mountPath: /var/www/exchat/media
          name: pinas-root
          subPath: scripts/git/Exchat_Social_Network/media      
        - mountPath: /var/www/exchat/static
          name: pinas-root
          subPath: scripts/git/Exchat_Social_Network/static     
        command:
          - /bin/sh
          - -c
          - |
            apt-get update
            apt-get install -y openssh-server
            apt-get install -y npm
            npm install -g @anthropic-ai/claude-code
            pip3 install -r requirements.txt
             # Configure SSH
            mkdir /var/run/sshd
            echo 'root:j7jwu12h' | chpasswd # <-- IMPORTANT: Change this password!
            sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
            # Start the SSH daemon in the background
            /usr/sbin/sshd &            
            /bin/bash
        workingDir: /var/www/exchat     
      imagePullSecrets:
      - name: github-container-registry
      restartPolicy: Always
      volumes:
      - name: pinas-root
        persistentVolumeClaim:
          claimName: pinas-root
      - name: exchat-secrets
        secret:
          defaultMode: 420
          optional: false
          secretName: exchat-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: exchat-dev-ssh
  namespace: weapps
spec:
  # This tells MetalLB to assign an external IP
  type: LoadBalancer 
  # This selector must match the labels on your pod template
  selector:
    app: exchat-dev-workload
  ports:
    - name: ssh
      protocol: TCP
      port: 22 # The port you will connect to from outside the cluster
      targetPort: 22 # The port the container is listening on (from the Deployment)    