apiVersion: apps/v1
kind: Deployment
metadata:
  name: exchat-dev-claude
  namespace: weapps
spec:
  selector:
    matchLabels:
      app: exchat-dev-claude
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: exchat-dev-claude
    spec:    
      containers:
      - envFrom:
        - secretRef:
            name: exchat-secrets
            optional: false
        image: python:3.10
        imagePullPolicy: Always
        name: exchat-dev-claude
        stdin: true
        ports:
        - containerPort: 8000
          name: exchat-dev-port
          protocol: TCP
        volumeMounts:
        - mountPath: /var/www/exchat
          name: pinas-root
          subPath: scripts/git/Exchat_Social_Network            
        - mountPath: /var/www/exchat/media
          name: pinas-root
          subPath: scripts/git/Exchat_Social_Network/media      
        - mountPath: /var/www/exchat/static
          name: pinas-root
          subPath: scripts/git/Exchat_Social_Network/static     
        command:
          - /bin/sh
          - -c
          - |
            apt-get update
            apt-get install -y npm
            npm install -g @anthropic-ai/claude-code
            pip3 install -r requirements.txt
            /bin/bash
        workingDir: /var/www/exchat     
      imagePullSecrets:
      - name: github-container-registry
      restartPolicy: Always
      volumes:
      - name: pinas-root
        persistentVolumeClaim:
          claimName: pinas-root
      - name: exchat-secrets
        secret:
          defaultMode: 420
          optional: false
          secretName: exchat-secrets