# Certificates for domains
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mynetapp-site
  namespace: weapps
spec:
  secretName: mynetapp-site-production-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.mynetapp.site"
  dnsNames:
  - "*.mynetapp.site"
  - "mynetapp.site"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: coparentcare-com-wildcard
  namespace: weapps
spec:
  # The secret that will be created and contain the TLS certificate and key.
  secretName: coparentcare-com-wildcard-tls

  # Use your production issuer once you have confirmed your setup with the staging issuer.
  issuerRef:
    name: letsencrypt-production # Changed from letsencrypt-staging
    kind: ClusterIssuer

  # The primary SAN. The first dnsName is also used as the Common Name.
  dnsNames:
  - "*.coparentcare.com"
  - "coparentcare.com"