# Cert-Manager Cluster Issuers

# LetsEncrypt Production
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: admin@weapps.com.au
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      # Specific solver for mynetapp.site
      - dns01:
          cloudflare:
            email: admin@weapps.com.au
            apiTokenSecretRef:
              name: cloudflare-token-secret
              key: cloudflare-token
            zoneID: "829321251e07c4dd078637aaef91f494"    
        selector:
          dnsZones:
            - "mynetapp.site"
      
      # Specific solver for coparentcare.com
      - dns01:
          cloudflare:
            email: admin@weapps.com.au
            apiTokenSecretRef:
              name: cloudflare-token-secret
              key: cloudflare-token
            zoneID: "b61fff41621defbffa011e4ecb0507cb"  
        selector:
          dnsZones:
            - "coparentcare.com"
          
      # HTTP-01 solver as fallback or for non-wildcard domains
      - http01:
          ingress:
            class: traefik
---
# LetsEncrypt Staging (for testing)
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: admin@weapps.com.au
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      # Specific solver for mynetapp.site
      - dns01:
          cloudflare:
            email: admin@weapps.com.au
            apiTokenSecretRef:
              name: cloudflare-token-secret
              key: cloudflare-token
        selector:
          dnsZones:
            - "mynetapp.site"
      
      # Specific solver for coparentcare.com
      - dns01:
          cloudflare:
            email: admin@weapps.com.au
            apiTokenSecretRef:
              name: cloudflare-token-secret
              key: cloudflare-token
        selector:
          dnsZones:
            - "coparentcare.com"
      
      # HTTP-01 solver as fallback or testing
      - http01:
          ingress:
            class: traefik
---
# Cloudflare API Token Secret
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-token-secret
  namespace: cert-manager
type: Opaque
data:
  # Replace with your actual Cloudflare token (base64 encoded)
  cloudflare-token: UmVwbGFjZSB0aGlzIHdpdGggeW91ciBhY3R1YWwgdG9rZW4=