apiVersion: v1
kind: Service
metadata:
  name: coparentcare-service
  namespace: weapps
spec:
  selector:
    app: coparentcare-workload
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: coparentcare-service-ingress
  namespace: weapps
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  rules:
  - host: www.coparentcare.com
    http:
      paths:
      - pathType: ImplementationSpecific
        backend:
          service:
            name: nginx-service
            port:
              number: 80
  tls:
  - hosts:
    - www.coparentcare.com
    secretName: coparentcare-com-tls
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coparentcare-deployment
  namespace: weapps
  annotations:
    keel.sh/policy: force   # Will update even when using 'latest' tag
    keel.sh/trigger: poll   # Enables active polling
    keel.sh/pollSchedule: "@every 1m"  # Check for updates every minute
spec:
  selector:
    matchLabels:
      app: coparentcare-workload
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: coparentcare-workload
    spec:    
      containers:
      - envFrom:
        - secretRef:
            name: exchat-secrets
            optional: false
        image: ghcr.io/foet/myexchat:latest
        imagePullPolicy: Always
        name: coparentcare-workload
        stdin: true
        ports:
        - containerPort: 8000
          name: coparent-port
          protocol: TCP
        volumeMounts:
        - mountPath: /var/www/exchat
          name: pinas-root
          subPath: scripts/git/Exchat_Social_Network            
        - mountPath: /var/www/exchat/media
          name: pinas-root
          subPath: scripts/git/Exchat_Social_Network/media      
        - mountPath: /var/www/exchat/static
          name: pinas-root
          subPath: scripts/git/Exchat_Social_Network/static     
      imagePullSecrets:
      - name: github-container-registry
      restartPolicy: Always
      volumes:
      - name: pinas-root
        persistentVolumeClaim:
          claimName: pinas-root