apiVersion: v1
kind: Service
metadata:
  name: nextcloud-service
  namespace: weapps
spec:
  selector:
    app: nextcloud-workload
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nextcloud-service-ingress
  namespace: weapps
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  rules:
  - host: nextcloud.mynetapp.site
    http:
      paths:
      - pathType: ImplementationSpecific
        backend:
          service:
            name: nginx-service
            port:
              number: 80
  tls:
  - hosts:
    - nextcloud.mynetapp.site
    secretName: mynetapp-site-production-tls      
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud-workload-deployment
  namespace: weapps
spec:
  selector:
    matchLabels:
      app: nextcloud-workload
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nextcloud-workload
    spec:
      containers:
      - name: nextcloud-workload
        image: nextcloud:fpm
        ports: 
        - containerPort: 9000
        volumeMounts:
        - mountPath: /var/www/html
          name: pinas-root
          subPath: docker/nextcloud/files
      restartPolicy: Always
      schedulerName: default-scheduler
      volumes:
      - name: pinas-root
        persistentVolumeClaim:
          claimName: pinas-root
      - configMap:
          defaultMode: 420
          name: linuxserver-map
          optional: false
        name: linuxserver-map