apiVersion: v1
data:
  CONNECTION_TOKEN: ajdqd3UxMmg=
  SUDO_PASSWORD: ajdqd3UxMmg=
kind: Secret
metadata:
  name: code-server-secret
  namespace: weapps
type: Opaque
---
apiVersion: v1
data:
  PGID: "1000"
  PUID: "1000"
  TZ: Australia/Brisbane
kind: ConfigMap
metadata:
  name: linuxserver-map-code
  namespace: weapps
---
apiVersion: v1
kind: Service
metadata:
  name: code-workload-service
  namespace: weapps
spec:
  selector:
    app: code-workload
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: code-workload-ingress
  namespace: weapps
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  rules:
  - host: code.mynetapp.site
    http:
      paths:
      - pathType: ImplementationSpecific
        backend:
          service:
            name: code-workload-service
            port:
              number: 80
  tls:
  - hosts:
    - code.mynetapp.site
    secretName: mynetapp-site-production-tls
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-workload-deployment
  namespace: weapps
spec:
  selector:
    matchLabels:
      app: code-workload
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: code-workload
    spec:
      containers:
      - name: code-workload
        envFrom:
        - configMapRef:
            name: linuxserver-map-code
            optional: false
        - secretRef:
            name: code-server-secret
            optional: false
        image: lscr.io/linuxserver/openvscode-server:latest
        ports: 
        - containerPort: 3000
        volumeMounts:
        - mountPath: /config/workspace
          name: pinas-scripts
          subPath: scripts/
        - mountPath: /config
          name: pinas-scripts
          subPath: docker/code
        - mountPath: /custom-cont-init.d
          name: pinas-scripts
          subPath: docker/code/custom-cont-init.d          
        - mountPath: /config/workspace/rancher
          name: pinas-scripts
          subPath: docker/ranchersetup  
      restartPolicy: Always
      schedulerName: default-scheduler
      volumes:
      - name: pinas-scripts
        persistentVolumeClaim:
          claimName: pinas-root
      - configMap:
          defaultMode: 420
          name: linuxserver-map-code
          optional: false
        name: code-map
      - name: code-secret
        secret:
          defaultMode: 420
          optional: false
          secretName: code-server-secret
