apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pinas-root
  namespace: weapps
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  storageClassName: local-path
---
# Add any additional common PVCs here